insert into Hotel (BuildingID, City, Zip) values (1, 'Xekar', null);
insert into Hotel (BuildingID, City, Zip) values (2, 'Przybiernów', '72-110');
insert into Hotel (BuildingID, City, Zip) values (3, 'Greensboro', '27499');
insert into Hotel (BuildingID, City, Zip) values (4, 'Le Lamentin', '97294 CEDEX 2');
insert into Hotel (BuildingID, City, Zip) values (5, 'Bhamo', null);
insert into Hotel (BuildingID, City, Zip) values (6, 'Mont-Laurier', 'J9L');
insert into Hotel (BuildingID, City, Zip) values (7, 'Lugu', null);
insert into Hotel (BuildingID, City, Zip) values (8, 'Kruševac', null);
insert into Hotel (BuildingID, City, Zip) values (9, 'Dřevohostice', '751 14');
insert into Hotel (BuildingID, City, Zip) values (10, 'Phetchabun', '45110');
insert into Hotel (BuildingID, City, Zip) values (11, 'Djibouti', null);
insert into Hotel (BuildingID, City, Zip) values (12, 'Puerto Guzmán', '861088');
insert into Hotel (BuildingID, City, Zip) values (13, 'Ålesund', '6005');
insert into Hotel (BuildingID, City, Zip) values (14, 'Anabar', null);
insert into Hotel (BuildingID, City, Zip) values (15, 'Haukipudas', '90840');
insert into Hotel (BuildingID, City, Zip) values (16, 'Sorochinsk', '461949');
insert into Hotel (BuildingID, City, Zip) values (17, 'Zhigulevsk', '445359');
insert into Hotel (BuildingID, City, Zip) values (18, 'Debre Werk’', null);
insert into Hotel (BuildingID, City, Zip) values (19, 'Padangcermin', null);
insert into Hotel (BuildingID, City, Zip) values (20, 'Kuala Lumpur', '50740');
insert into Hotel (BuildingID, City, Zip) values (21, 'Joinville', '89200-000');
insert into Hotel (BuildingID, City, Zip) values (22, 'Pérez', '2121');
insert into Hotel (BuildingID, City, Zip) values (23, 'Gominhães', '4800-424');
insert into Hotel (BuildingID, City, Zip) values (24, 'Lublin', '20-960');
insert into Hotel (BuildingID, City, Zip) values (25, 'Berlin', '12307');
insert into Hotel (BuildingID, City, Zip) values (26, 'Gemena', null);
insert into Hotel (BuildingID, City, Zip) values (27, 'Huangzhawan', null);
insert into Hotel (BuildingID, City, Zip) values (28, 'San Isidro', '8421');
insert into Hotel (BuildingID, City, Zip) values (29, 'Mayma', '659780');
insert into Hotel (BuildingID, City, Zip) values (30, 'Bajia', null);
insert into Hotel (BuildingID, City, Zip) values (31, 'Ganshui', null);
insert into Hotel (BuildingID, City, Zip) values (32, 'Rio Preto da Eva', '69115-000');
insert into Hotel (BuildingID, City, Zip) values (33, 'Jingyu', null);
insert into Hotel (BuildingID, City, Zip) values (34, 'As Saddah', null);
insert into Hotel (BuildingID, City, Zip) values (35, 'Chengnan', null);
insert into Hotel (BuildingID, City, Zip) values (36, 'Cúcuta', '540019');
insert into Hotel (BuildingID, City, Zip) values (37, 'Sortavala', '186793');
insert into Hotel (BuildingID, City, Zip) values (38, 'Bijeli', null);
insert into Hotel (BuildingID, City, Zip) values (39, 'Knivsta', '741 96');
insert into Hotel (BuildingID, City, Zip) values (40, 'Tazarine', null);
insert into Hotel (BuildingID, City, Zip) values (41, 'Yong’an', null);
insert into Hotel (BuildingID, City, Zip) values (42, 'Břasy', '338 24');
insert into Hotel (BuildingID, City, Zip) values (43, 'Ashcroft', 'L0R');
insert into Hotel (BuildingID, City, Zip) values (44, 'El Aguacate', '40687');
insert into Hotel (BuildingID, City, Zip) values (45, 'Jingang', null);
insert into Hotel (BuildingID, City, Zip) values (46, 'Rocky Mountain House', 'T4T');
insert into Hotel (BuildingID, City, Zip) values (47, 'Jhingergācha', '7420');
insert into Hotel (BuildingID, City, Zip) values (48, 'Tamanan', null);
insert into Hotel (BuildingID, City, Zip) values (49, 'Carrières-sur-Seine', '78424 CEDEX');
insert into Hotel (BuildingID, City, Zip) values (50, 'Nanhuatang', null);
insert into Hotel (BuildingID, City, Zip) values (51, 'Paris 03', '75151 CEDEX 03');
insert into Hotel (BuildingID, City, Zip) values (52, 'Tangxing', null);
insert into Hotel (BuildingID, City, Zip) values (53, 'Kebonsari', null);
insert into Hotel (BuildingID, City, Zip) values (54, 'Panawuan', null);
insert into Hotel (BuildingID, City, Zip) values (55, 'Linköping', '586 63');
insert into Hotel (BuildingID, City, Zip) values (56, 'Kajiado', null);
insert into Hotel (BuildingID, City, Zip) values (57, 'Campurrejo', null);
insert into Hotel (BuildingID, City, Zip) values (58, 'Zhongbu', null);
insert into Hotel (BuildingID, City, Zip) values (59, 'Kovdor', '633375');
insert into Hotel (BuildingID, City, Zip) values (60, 'Sveg', '842 93');
insert into Hotel (BuildingID, City, Zip) values (61, 'Göteborg', '403 13');
insert into Hotel (BuildingID, City, Zip) values (62, 'Grabów nad Prosną', '90-510');
insert into Hotel (BuildingID, City, Zip) values (63, 'Lianokládhion', null);
insert into Hotel (BuildingID, City, Zip) values (64, 'Quebo', null);
insert into Hotel (BuildingID, City, Zip) values (65, 'Portalegre', '7300-006');
insert into Hotel (BuildingID, City, Zip) values (66, 'Zhangjiabao', null);
insert into Hotel (BuildingID, City, Zip) values (67, 'Embu', '06800-000');
insert into Hotel (BuildingID, City, Zip) values (68, 'Rantīs', null);
insert into Hotel (BuildingID, City, Zip) values (69, 'Dong Liang’erzhuang', null);
insert into Hotel (BuildingID, City, Zip) values (70, 'Palhoça', '88130-000');
insert into Hotel (BuildingID, City, Zip) values (71, 'Tucson', '85754');
insert into Hotel (BuildingID, City, Zip) values (72, 'Yimamu', null);
insert into Hotel (BuildingID, City, Zip) values (73, 'Uchaly', '453703');
insert into Hotel (BuildingID, City, Zip) values (74, 'Borek Wielkopolski', '63-810');
insert into Hotel (BuildingID, City, Zip) values (75, 'Jiuxian', null);
insert into Hotel (BuildingID, City, Zip) values (76, 'Åmål', '662 24');
insert into Hotel (BuildingID, City, Zip) values (77, 'Jiale', null);
insert into Hotel (BuildingID, City, Zip) values (78, 'Tarczyn', '05-555');
insert into Hotel (BuildingID, City, Zip) values (79, 'Mpanda', null);
insert into Hotel (BuildingID, City, Zip) values (80, 'Lamotrek', null);
insert into Hotel (BuildingID, City, Zip) values (81, 'Oepuah', null);
insert into Hotel (BuildingID, City, Zip) values (82, 'Södertälje', '151 22');
insert into Hotel (BuildingID, City, Zip) values (83, 'Pato Branco', '85500-000');
insert into Hotel (BuildingID, City, Zip) values (84, 'Erfurt', '99089');
insert into Hotel (BuildingID, City, Zip) values (85, 'Placer', '8405');
insert into Hotel (BuildingID, City, Zip) values (86, 'Batuna Satu', null);
insert into Hotel (BuildingID, City, Zip) values (87, 'Luruaco', '085068');
insert into Hotel (BuildingID, City, Zip) values (88, 'Agbani', null);
insert into Hotel (BuildingID, City, Zip) values (89, 'Bogor', null);
insert into Hotel (BuildingID, City, Zip) values (90, 'Muarapinang', null);
insert into Hotel (BuildingID, City, Zip) values (91, 'Al Qārah', null);
insert into Hotel (BuildingID, City, Zip) values (92, 'Kayima', null);
insert into Hotel (BuildingID, City, Zip) values (93, 'Velyki Mezhyrichi', null);
insert into Hotel (BuildingID, City, Zip) values (94, 'Gatbo', '4419');
insert into Hotel (BuildingID, City, Zip) values (95, 'Chengmen', null);
insert into Hotel (BuildingID, City, Zip) values (96, 'Kumba', null);
insert into Hotel (BuildingID, City, Zip) values (97, 'Church End', 'N3');
insert into Hotel (BuildingID, City, Zip) values (98, 'Trojanów', '08-455');
insert into Hotel (BuildingID, City, Zip) values (99, 'Sé', '5100-121');
insert into Hotel (BuildingID, City, Zip) values (100, 'Puerto Varas', null);
