insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (1, 'Pineapple - Golden', 'Otaria flavescens', '$2.14');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (2, 'Coffee Decaf Colombian', 'Chlidonias leucopterus', '$4.32');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (3, 'Nantucket Cranberry Juice', 'Porphyrio porphyrio', '$7.94');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (4, 'Sauce - Vodka Blush', 'Marmota caligata', '$5.08');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (5, 'Durian Fruit', 'Phalaropus fulicarius', '$7.14');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (6, 'Lettuce - Mini Greens, Whole', 'Helogale undulata', '$2.36');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (7, 'Broom - Angled', 'Potos flavus', '$8.15');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (8, 'Bread - Hot Dog Buns', 'Ovis ammon', '$3.76');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (9, 'Mikes Hard Lemonade', 'Ovis dalli stonei', '$3.02');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (10, 'The Pop Shoppe - Root Beer', 'Acridotheres tristis', '$4.11');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (11, 'Jolt Cola - Electric Blue', 'Ploceus intermedius', '$7.01');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (12, 'Blue Curacao - Marie Brizard', 'Acridotheres tristis', '$1.37');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (13, 'Wine - Red, Cabernet Merlot', 'Deroptyus accipitrinus', '$7.70');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (14, 'Scrubbie - Scotchbrite Hand Pad', 'Gopherus agassizii', '$8.29');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (15, 'Appetizer - Mango Chevre', 'Colaptes campestroides', '$7.46');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (16, 'Chicken - Whole Fryers', 'Streptopelia decipiens', '$5.45');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (17, 'Bagelers', 'Alcelaphus buselaphus caama', '$6.36');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (18, 'Yokaline', 'Tragelaphus angasi', '$6.20');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (19, 'Bay Leaf Ground', 'Antidorcas marsupialis', '$4.74');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (20, 'Cod - Black Whole Fillet', 'Spizaetus coronatus', '$2.25');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (21, 'Crab - Meat Combo', 'Gazella thompsonii', '$7.21');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (22, 'Beans - Fava Fresh', 'unavailable', '$4.04');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (23, 'Sprouts - Peppercress', 'Choriotis kori', '$5.63');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (24, 'Pea - Snow', 'Pelecans onocratalus', '$0.80');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (25, 'Cheese - Brie Roitelet', 'Aonyx cinerea', '$6.18');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (26, 'Syrup - Monin, Amaretta', 'Anathana ellioti', '$6.03');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (27, 'Wine - White, Schroder And Schyl', 'Alopochen aegyptiacus', '$4.89');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (28, 'Chips Potato All Dressed - 43g', 'Diceros bicornis', '$2.54');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (29, 'Energy - Boo - Koo', 'Speotyte cuniculata', '$0.73');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (30, 'Strawberries', 'Hymenolaimus malacorhynchus', '$2.95');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (31, 'Star Anise, Whole', 'Ctenophorus ornatus', '$8.83');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (32, 'Crab - Blue, Frozen', 'Ratufa indica', '$6.58');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (33, 'Iced Tea - Lemon, 340ml', 'Ciconia episcopus', '$5.34');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (34, 'Glycerine', 'Damaliscus dorcas', '$1.87');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (35, 'Muffin Hinge 117n', 'Larus novaehollandiae', '$3.85');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (36, 'Wine - Touraine Azay - Le - Rideau', 'Conolophus subcristatus', '$7.12');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (37, 'Bread - Crumbs, Bulk', 'Castor canadensis', '$1.79');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (38, 'Pastry - Banana Tea Loaf', 'Larus novaehollandiae', '$7.81');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (39, 'Mix - Cocktail Ice Cream', 'Taxidea taxus', '$1.18');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (40, 'Shrimp - Black Tiger 13/15', 'Milvus migrans', '$9.32');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (41, 'Table Cloth 53x69 White', 'Egretta thula', '$2.95');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (42, 'Beef - Ground Lean Fresh', 'Spizaetus coronatus', '$7.63');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (43, 'Raisin - Golden', 'Phalacrocorax carbo', '$7.16');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (44, 'Bread Ww Cluster', 'Chlamydosaurus kingii', '$9.15');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (45, 'Onions - Green', 'Cervus duvauceli', '$8.41');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (46, 'Beef - Tenderloin - Aa', 'Morelia spilotes variegata', '$7.65');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (47, 'Lettuce - Red Leaf', 'Erinaceus frontalis', '$0.17');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (48, 'Salmon - Atlantic, No Skin', 'Zalophus californicus', '$2.16');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (49, 'Coke - Diet, 355 Ml', 'Upupa epops', '$3.39');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (50, 'Table Cloth 144x90 White', 'Tockus flavirostris', '$5.03');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (51, 'Beer - Heinekin', 'Bugeranus caruncalatus', '$2.45');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (52, 'Cumin - Whole', 'Eudromia elegans', '$3.56');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (53, 'Chocolate Bar - Coffee Crisp', 'Funambulus pennati', '$4.38');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (54, 'Extract - Vanilla,artificial', 'Microcavia australis', '$0.16');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (55, 'Tomatoes', 'Salvadora hexalepis', '$4.96');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (56, 'Salmon - Atlantic, No Skin', 'Spheniscus magellanicus', '$3.06');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (57, 'Instant Coffee', 'Acrantophis madagascariensis', '$6.13');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (58, 'Garlic - Peeled', 'Macaca mulatta', '$1.21');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (59, 'Squash - Pattypan, Yellow', 'Gazella thompsonii', '$6.90');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (60, 'Foam Dinner Plate', 'Anser caerulescens', '$2.94');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (61, 'Honey - Lavender', 'Trichosurus vulpecula', '$9.82');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (62, 'Sproutsmustard Cress', 'Dasyurus maculatus', '$7.02');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (63, 'Cake Circle, Paprus', 'Ara ararauna', '$5.34');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (64, 'Wine - White, Antinore Orvieto', 'Haliaeetus leucocephalus', '$8.11');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (65, 'Soup - Campbellschix Stew', 'Sula nebouxii', '$9.65');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (66, 'Shiro Miso', 'Sarcophilus harrisii', '$9.77');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (67, 'Cake - Box Window 10x10x2.5', 'Gazella thompsonii', '$7.13');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (68, 'Ranchero - Primerba, Paste', 'Eumetopias jubatus', '$2.03');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (69, 'French Pastry - Mini Chocolate', 'Larus fuliginosus', '$0.97');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (70, 'Flower - Commercial Bronze', 'Potos flavus', '$2.05');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (71, 'Absolut Citron', 'Spheniscus magellanicus', '$8.61');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (72, 'Chinese Foods - Plain Fried Rice', 'Melursus ursinus', '$0.90');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (73, 'Truffle Shells - White Chocolate', 'Phalacrocorax carbo', '$6.15');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (74, 'Garlic - Primerba, Paste', 'Didelphis virginiana', '$3.58');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (75, 'Beer - True North Lager', 'Chordeiles minor', '$6.34');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (76, 'Vinegar - White', 'Phoenicopterus chilensis', '$8.43');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (77, 'Placemat - Scallop, White', 'Vulpes chama', '$8.95');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (78, 'Nougat - Paste / Cream', 'Varanus albigularis', '$7.24');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (79, 'Eggplant Italian', 'Proteles cristatus', '$6.14');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (80, 'Muffin Chocolate Individual Wrap', 'Ardea cinerea', '$9.39');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (81, 'Wine - White, Ej', 'Odocoileus hemionus', '$9.70');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (82, 'Oyster - In Shell', 'Larus dominicanus', '$2.10');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (83, 'Bonito Flakes - Toku Katsuo', 'Haliaetus leucogaster', '$9.55');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (84, 'Tart - Raisin And Pecan', 'unavailable', '$3.66');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (85, 'Table Cloth 90x90 Colour', 'Anas bahamensis', '$5.13');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (86, 'Salami - Genova', 'unavailable', '$5.57');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (87, 'Bread - Dark Rye, Loaf', 'Merops bullockoides', '$7.60');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (88, 'Wine - Red, Black Opal Shiraz', 'Potos flavus', '$2.16');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (89, 'Bag - Regular Kraft 20 Lb', 'Ara macao', '$8.44');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (90, 'Chicken - Ground', 'Tringa glareola', '$3.30');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (91, 'Syrup - Monin, Irish Cream', 'Ephipplorhynchus senegalensis', '$5.55');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (92, 'Bar Mix - Lime', 'Tadorna tadorna', '$5.39');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (93, 'Container - Hngd Cll Blk 7x7x3', 'unavailable', '$3.87');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (94, 'Cabbage - Green', 'Cercatetus concinnus', '$7.04');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (95, 'Cheese - Parmigiano Reggiano', 'Tachyglossus aculeatus', '$3.55');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (96, 'Pastry - Plain Baked Croissant', 'Grus canadensis', '$4.72');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (97, 'Sole - Dover, Whole, Fresh', 'Tenrec ecaudatus', '$5.60');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (98, 'Pepper - Gypsy Pepper', 'Bubo virginianus', '$9.91');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (99, 'Bread - Sticks, Thin, Plain', 'Echimys chrysurus', '$2.40');
insert into Product (PrdID, PrdName, PrdDescription, PrdCost) values (100, 'Brocolinni - Gaylan, Chinese', 'Pseudoleistes virescens', '$5.62');
